product_mapping = {
    '1 way Comprehensive Plan': 'comprehensive',
    '2 way Comprehensive Plan': 'comprehensive',
    '24 Protect': 'cancellation',
    'Annual Gold Plan': 'amt',
    'Annual Silver Plan': 'amt',
    'Annual Travel Protect Gold': 'amt',
    'Annual Travel Protect Platinum': 'amt',
    'Annual Travel Protect Silver': 'amt',
    'Basic Plan': 'standard',
    'Bronze Plan': 'standard',
    'Cancellation Plan': 'cancellation',
    'Child Comprehensive Plan': 'comprehensive',
    'Comprehensive Plan': 'comprehensive',
    'Gold Plan': 'comprehensive',
    'Individual Comprehensive Plan': 'comprehensive',
    'Premier Plan': 'comprehensive',
    'Rental Vehicle Excess Insurance': 'rental',
    'Silver Plan': 'standard',
    'Single Trip Travel Protect Gold': 'comprehensive',
    'Single Trip Travel Protect Platinum': 'comprehensive',
    'Single Trip Travel Protect Silver': 'standard',
    'Spouse or Parents Comprehensive Plan': 'comprehensive',
    'Ticket Protector': 'cancellation',
    'Travel Cruise Protect': 'cancellation',
    'Travel Cruise Protect Family': 'cancellation',
    'Value Plan': 'standard'
}
